"""Video generation and editing with Gemini Omni.

| Copyright 2017-2026, Voxel51, Inc.
| `voxel51.com <https://voxel51.com/>`_
|
"""

import base64
import os
import time

import requests

import fiftyone as fo

from . import gemini_media as gm


INTERACTIONS_URL = gm.INTERACTIONS_URL

VIDEO_GEN_MODELS = [
    "gemini-omni-1.1-flash",
    "gemini-omni-flash-preview",
]

DEFAULT_VIDEO_GEN_MODEL = "gemini-omni-1.1-flash"

RESOLUTIONS = ["360p", "720p", "1080p", "4k"]
ASPECT_RATIOS = ["16:9", "9:16"]

REQUEST_TIMEOUT = gm.REQUEST_TIMEOUT

IMAGE_MIME_TYPES = {
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
}


class GeminiVideoGenError(Exception):
    """Raised when a video generation request cannot be completed."""


GENERATION_TASKS = {
    "text_to_video": {
        "label": "Text to video",
        "description": "Generate a clip from a written description",
        "needs": "none",
        "prompt_help": "Describe the shot, the motion, and the sound you want",
    },
    "image_to_video": {
        "label": "Image to video",
        "description": "Animate one selected image",
        "needs": "one_image",
        "prompt_help": "Describe how the still should move, e.g. 'slow push-in'",
    },
    "first_last_frame": {
        "label": "First and last frame",
        "description": "Interpolate between two selected images",
        "needs": "two_images",
        "prompt_help": "Describe the transition between the two frames",
    },
    "reference_to_video": {
        "label": "Reference to video",
        "description": "Generate a clip that keeps selected subjects consistent",
        "needs": "images",
        "prompt_help": "Describe the scene the referenced subjects should appear in",
    },
    "edit": {
        "label": "Edit a generated clip",
        "description": "Refine a clip this plugin generated, in natural language",
        "needs": "generated_video",
        "prompt_help": "Describe the change, e.g. 'make it night time'",
    },
    "extend": {
        "label": "Extend a generated clip",
        "description": "Continue a clip this plugin generated by up to 10 seconds",
        "needs": "generated_video",
        "prompt_help": "Describe what happens next",
    },
}

STATEFUL_TASKS = {"edit", "extend"}


def resolve_task(task):
    """Resolves a generation task name.

    Args:
        task: a key of :data:`GENERATION_TASKS`

    Returns:
        a ``(name, task)`` tuple

    Raises:
        GeminiVideoGenError: if the task is unknown
    """
    spec = GENERATION_TASKS.get(task)
    if spec is None:
        raise GeminiVideoGenError(
            f"Unknown generation task '{task}'. Available tasks: "
            + ", ".join(sorted(GENERATION_TASKS))
        )

    return task, spec


def get_image_mime_type(path):
    """Returns the MIME type for an image path."""
    ext = os.path.splitext(path)[1].lstrip(".").lower()
    return IMAGE_MIME_TYPES.get(ext, "image/jpeg")


def build_input(prompt, image_paths=None):
    """Builds the ``input`` list for a generation request.

    Args:
        prompt: the text prompt
        image_paths (None): image paths to send as sources or references

    Returns:
        a list of input parts
    """
    parts = []
    for path in image_paths or []:
        if not os.path.isfile(path):
            raise GeminiVideoGenError(f"Image not found: {path}")

        parts.append({
            "type": "image",
            "data": gm.encode_file(path),
            "mime_type": get_image_mime_type(path),
        })

    parts.append({"type": "text", "text": prompt})
    return parts


def extract_video(response, api_key, timeout=REQUEST_TIMEOUT):
    """Extracts the generated video bytes from an Interactions response.

    Args:
        response: the parsed Interactions API response
        api_key: a Gemini API key
        timeout (900): seconds to wait for a URI-delivered file

    Returns:
        the video bytes

    Raises:
        GeminiVideoGenError: if no video can be recovered
    """
    for step in response.get("steps", []):
        if step.get("type") != "model_output":
            continue

        for item in step.get("content", []):
            if item.get("type") == "video" and item.get("data"):
                return base64.b64decode(item["data"])

    uri = (response.get("output_video") or {}).get("uri")
    if not uri:
        raise GeminiVideoGenError(
            f"No video in the response (status: {response.get('status')})"
        )

    deadline = time.time() + timeout
    while time.time() < deadline:
        resp = requests.get(
            uri, headers={"x-goog-api-key": api_key}, timeout=120
        )
        if resp.status_code == 200 and resp.content:
            return resp.content

        time.sleep(3)

    raise GeminiVideoGenError(f"Timed out downloading the generated video: {uri}")


def generate_video(
    prompt,
    api_key,
    task="text_to_video",
    model=DEFAULT_VIDEO_GEN_MODEL,
    image_paths=None,
    previous_interaction_id=None,
    aspect_ratio="16:9",
    resolution="720p",
    timeout=REQUEST_TIMEOUT,
):
    """Generates, edits or extends a video.

    Args:
        prompt: the instruction
        api_key: a Gemini API key
        task ("text_to_video"): a key of :data:`GENERATION_TASKS`
        model: the Omni model to use
        image_paths (None): source or reference images
        previous_interaction_id (None): the clip to edit or extend
        aspect_ratio ("16:9"): ``"16:9"`` or ``"9:16"``
        resolution ("720p"): one of :data:`RESOLUTIONS`
        timeout (900): the request timeout, in seconds

    Returns:
        a dict with ``video`` bytes, ``interaction_id``, ``usage``, ``task``,
        ``prompt``, ``model``, ``aspect_ratio`` and ``resolution`` keys

    Raises:
        GeminiVideoGenError: if the request fails
    """
    name, spec = resolve_task(task)

    prompt = (prompt or "").strip()
    if not prompt:
        raise GeminiVideoGenError(f"The '{name}' task requires a prompt")

    if name in STATEFUL_TASKS and not previous_interaction_id:
        raise GeminiVideoGenError(
            f"The '{name}' task needs a clip generated by this plugin to work "
            "from. Select a generated video sample."
        )

    payload = {
        "model": model,
        "input": build_input(prompt, image_paths),
        "response_format": {
            "type": "video",
            "aspect_ratio": aspect_ratio,
            "resolution": resolution,
            "delivery": "inline",
        },
    }

    if previous_interaction_id:
        payload["previous_interaction_id"] = previous_interaction_id
    else:
        payload["generation_config"] = {"video_config": {"task": name}}

    resp = requests.post(
        INTERACTIONS_URL,
        headers={"x-goog-api-key": api_key, "Content-Type": "application/json"},
        json=payload,
        timeout=timeout,
    )

    try:
        content = resp.json()
    except ValueError:
        raise GeminiVideoGenError(
            f"Gemini returned a non-JSON response: {resp.text[:300]}"
        )

    if "error" in content:
        err = content["error"]
        raise GeminiVideoGenError(err.get("message") or str(err))

    return {
        "task": name,
        "prompt": prompt,
        "model": model,
        "aspect_ratio": aspect_ratio,
        "resolution": resolution,
        "video": extract_video(content, api_key, timeout=timeout),
        "interaction_id": content.get("id"),
        "usage": gm.summarize_usage(content),
    }


def target_dataset(dataset):
    """Returns the dataset generated clips should be added to.

    Args:
        dataset: the current :class:`fiftyone.core.dataset.Dataset`

    Returns:
        a ``(dataset, created)`` tuple
    """
    if dataset.media_type == "video":
        return dataset, False

    name = f"{dataset.name}-gemini-video"
    if fo.dataset_exists(name):
        return fo.load_dataset(name), False

    return fo.Dataset(name, persistent=True), True


def save_video(dataset, result, output_dir=None, source_ids=None):
    """Writes a generated clip to disk and adds it as a sample.

    Args:
        dataset: the current :class:`fiftyone.core.dataset.Dataset`
        result: a :func:`generate_video` result
        output_dir (None): where to write the clip. Defaults to a
            ``gemini_generated`` folder beside the dataset's media, so a clip
            generated on a cloud-backed Enterprise dataset lands in the same
            bucket and stays visible to everyone
        source_ids (None): ids of the samples the generation drew on

    Returns:
        a dict with ``dataset``, ``sample_id``, ``filepath`` and ``created``
    """
    target, created = target_dataset(dataset)

    destination = output_dir or gm.media_root(dataset)
    stem = result["task"]
    if source_ids:
        try:
            anchor = dataset[list(source_ids)[0]]
            stem = f"{stem}_{os.path.splitext(os.path.basename(anchor.filepath))[0]}"
        except Exception:
            pass

    filepath = gm.output_path(destination, stem, "mp4")
    gm.write_media(result["video"], filepath)

    sample = fo.Sample(filepath=filepath)
    sample["prompt"] = result["prompt"]
    sample["generation_type"] = result["task"]
    sample["gemini_model"] = result["model"]
    sample["gemini_interaction_id"] = result["interaction_id"]
    sample["resolution"] = result["resolution"]
    sample["aspect_ratio"] = result["aspect_ratio"]
    if source_ids:
        sample["source_sample_ids"] = list(source_ids)

    target.add_sample(sample)
    sample.compute_metadata()
    sample.save()

    return {
        "dataset": target.name,
        "sample_id": sample.id,
        "filepath": filepath,
        "created": created,
        "duration": sample.metadata.duration if sample.metadata else None,
    }
